version: '3.8'

services:
  app:
    container_name: book-rental-container
    image: my-docker-registry/book-rental-app:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:mysql://db:3306/book_rental
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: book-rental-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: book_rental
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: