server:
    port: 8080

spring:
    application:
        name: BookRental
    profiles:
        active: dev  # 기본 활성화 프로필

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    cache:
        type: simple
    jwt:
        secret: aa59df3bbeabb76fa3d7a1cc54619384bc1aacee9274774914f11fb9b90f387c

---
# 개발 환경(dev)
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:mysql://localhost:3306/bookRental
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

---
# 운영 환경(prod)
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: jdbc:mysql://prod-db:3306/proddb
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver